version: '2'

services:
  shopping-cart-app:
    image: 'shopping-cart-app:latest'
    build:
      context: .
    ports:
      - 8080:8080
    container_name: shopping-cart-app
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Pass2020!
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgres-db:
    image: 'postgres:13.1-alpine'
    ports:
      - 5432:5432
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pass2020!